// Code generated for Kin agent discovery. DO NOT EDIT BY HAND without care.
// Source: vercel-labs/skills (npm package "skills") AGENTS table — skill install targets.
// Purpose: scientific discovery catalog (local presence). Not a first-class runner list.
// Snapshot: skills@1.5.19 dist/cli.mjs agent definitions.

package detect

// DiscoverySpec describes one agent that may be present on the machine.
// Presence is best-effort: PATH binaries and/or well-known config directories
// (the same signals npx skills uses when choosing skill install targets).
type DiscoverySpec struct {
	ID           string
	Name         string
	Bins         []string // optional CLI names on PATH
	EnvBin       string   // optional absolute-path override env
	HomeDirs     []string // paths relative to $HOME
	ConfigDirs   []string // paths relative to XDG config home (~/.config)
	SkillsDir    string   // project-relative skills dir (skills ecosystem)
	Priority     int      // lower = preferred when ranking discoveries
	RunnableHint bool     // true when Kin has a first-class process adapter
}

// SkillsDiscoveryCatalog is the skills-ecosystem agent list for local discovery
// (e.g. when choosing agent.default). Entries that are not Kin-runnable may still
// report presence; only registered adapters can become the session host.
func SkillsDiscoveryCatalog() []DiscoverySpec {
	return []DiscoverySpec{
		{
			ID:           "claude-code",
			Name:         "Claude Code",
			Bins:         []string{"claude"},
			EnvBin:       "KIN_CLAUDE_BIN",
			HomeDirs:     []string{".claude"},
			ConfigDirs:   nil,
			SkillsDir:    ".claude/skills",
			Priority:     10,
			RunnableHint: true,
		},
		{
			ID:           "codex",
			Name:         "Codex",
			Bins:         []string{"codex"},
			EnvBin:       "KIN_CODEX_BIN",
			HomeDirs:     []string{".codex"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     20,
			RunnableHint: true,
		},
		{
			ID:           "gemini-cli",
			Name:         "Gemini CLI",
			Bins:         []string{"gemini"},
			EnvBin:       "KIN_GEMINI_BIN",
			HomeDirs:     []string{".gemini"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     40,
			RunnableHint: false,
		},
		{
			ID:           "opencode",
			Name:         "OpenCode",
			Bins:         []string{"opencode"},
			EnvBin:       "KIN_OPENCODE_BIN",
			HomeDirs:     nil,
			ConfigDirs:   []string{"opencode"},
			SkillsDir:    ".agents/skills",
			Priority:     50,
			RunnableHint: false,
		},
		{
			ID:           "openclaw",
			Name:         "OpenClaw",
			Bins:         []string{"openclaw"},
			EnvBin:       "KIN_OPENCLAW_BIN",
			HomeDirs:     []string{".openclaw", ".clawdbot", ".moltbot"},
			ConfigDirs:   nil,
			SkillsDir:    "skills",
			Priority:     60,
			RunnableHint: false,
		},
		{
			ID:           "qoder",
			Name:         "Qoder",
			Bins:         []string{"qoder"},
			EnvBin:       "KIN_QODER_BIN",
			HomeDirs:     []string{".qoder"},
			ConfigDirs:   nil,
			SkillsDir:    ".qoder/skills",
			Priority:     70,
			RunnableHint: false,
		},
		{
			ID:           "qoder-cn",
			Name:         "Qoder CN",
			Bins:         []string{"qoder"},
			EnvBin:       "KIN_QODER_BIN",
			HomeDirs:     []string{".qoder-cn"},
			ConfigDirs:   nil,
			SkillsDir:    ".qoder/skills",
			Priority:     71,
			RunnableHint: false,
		},
		{
			ID:           "cursor",
			Name:         "Cursor",
			Bins:         []string{"cursor", "cursor-agent"},
			EnvBin:       "KIN_CURSOR_BIN",
			HomeDirs:     []string{".cursor"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     80,
			RunnableHint: false,
		},
		{
			ID:           "windsurf",
			Name:         "Windsurf",
			Bins:         []string{"windsurf"},
			EnvBin:       "KIN_WINDSURF_BIN",
			HomeDirs:     []string{".windsurf", ".codeium/windsurf"},
			ConfigDirs:   nil,
			SkillsDir:    ".windsurf/skills",
			Priority:     90,
			RunnableHint: false,
		},
		{
			ID:           "aider-desk",
			Name:         "AiderDesk",
			Bins:         []string{"aider"},
			EnvBin:       "KIN_AIDER_BIN",
			HomeDirs:     []string{".aider-desk"},
			ConfigDirs:   nil,
			SkillsDir:    ".aider-desk/skills",
			Priority:     100,
			RunnableHint: false,
		},
		{
			ID:           "qwen-code",
			Name:         "Qwen Code",
			Bins:         []string{"qwen"},
			EnvBin:       "KIN_QWEN_BIN",
			HomeDirs:     []string{".qwen"},
			ConfigDirs:   nil,
			SkillsDir:    ".qwen/skills",
			Priority:     110,
			RunnableHint: false,
		},
		{
			ID:           "goose",
			Name:         "Goose",
			Bins:         []string{"goose"},
			EnvBin:       "KIN_GOOSE_BIN",
			HomeDirs:     nil,
			ConfigDirs:   []string{"goose"},
			SkillsDir:    ".goose/skills",
			Priority:     120,
			RunnableHint: false,
		},
		{
			ID:           "kilo",
			Name:         "Kilo Code",
			Bins:         []string{"kilo"},
			EnvBin:       "KIN_KILO_BIN",
			HomeDirs:     []string{".kilocode"},
			ConfigDirs:   nil,
			SkillsDir:    ".kilocode/skills",
			Priority:     130,
			RunnableHint: false,
		},
		{
			ID:           "adal",
			Name:         "AdaL",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".adal"},
			ConfigDirs:   nil,
			SkillsDir:    ".adal/skills",
			Priority:     514,
			RunnableHint: false,
		},
		{
			ID:           "amp",
			Name:         "Amp",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   []string{"amp"},
			SkillsDir:    ".agents/skills",
			Priority:     515,
			RunnableHint: false,
		},
		{
			ID:           "antigravity",
			Name:         "Antigravity",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".gemini/antigravity"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     516,
			RunnableHint: false,
		},
		{
			ID:           "antigravity-cli",
			Name:         "Antigravity CLI",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".gemini/antigravity-cli"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     517,
			RunnableHint: false,
		},
		{
			ID:           "astrbot",
			Name:         "AstrBot",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".astrbot"},
			ConfigDirs:   nil,
			SkillsDir:    "data/skills",
			Priority:     518,
			RunnableHint: false,
		},
		{
			ID:           "augment",
			Name:         "Augment",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".augment"},
			ConfigDirs:   nil,
			SkillsDir:    ".augment/skills",
			Priority:     519,
			RunnableHint: false,
		},
		{
			ID:           "autohand-code",
			Name:         "Autohand Code CLI",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    ".autohand/skills",
			Priority:     520,
			RunnableHint: false,
		},
		{
			ID:           "bob",
			Name:         "IBM Bob",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".bob"},
			ConfigDirs:   nil,
			SkillsDir:    ".bob/skills",
			Priority:     521,
			RunnableHint: false,
		},
		{
			ID:           "cline",
			Name:         "Cline",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".cline"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     522,
			RunnableHint: false,
		},
		{
			ID:           "codearts-agent",
			Name:         "CodeArts Agent",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".codeartsdoer"},
			ConfigDirs:   nil,
			SkillsDir:    ".codeartsdoer/skills",
			Priority:     523,
			RunnableHint: false,
		},
		{
			ID:           "codebuddy",
			Name:         "CodeBuddy",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".codebuddy"},
			ConfigDirs:   nil,
			SkillsDir:    ".codebuddy/skills",
			Priority:     524,
			RunnableHint: false,
		},
		{
			ID:           "codemaker",
			Name:         "Codemaker",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".codemaker"},
			ConfigDirs:   nil,
			SkillsDir:    ".codemaker/skills",
			Priority:     525,
			RunnableHint: false,
		},
		{
			ID:           "codestudio",
			Name:         "Code Studio",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".codestudio"},
			ConfigDirs:   nil,
			SkillsDir:    ".codestudio/skills",
			Priority:     526,
			RunnableHint: false,
		},
		{
			ID:           "command-code",
			Name:         "Command Code",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".commandcode"},
			ConfigDirs:   nil,
			SkillsDir:    ".commandcode/skills",
			Priority:     527,
			RunnableHint: false,
		},
		{
			ID:           "continue",
			Name:         "Continue",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".continue"},
			ConfigDirs:   nil,
			SkillsDir:    ".continue/skills",
			Priority:     528,
			RunnableHint: false,
		},
		{
			ID:           "cortex",
			Name:         "Cortex Code",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".snowflake/cortex"},
			ConfigDirs:   nil,
			SkillsDir:    ".cortex/skills",
			Priority:     529,
			RunnableHint: false,
		},
		{
			ID:           "crush",
			Name:         "Crush",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".config/crush"},
			ConfigDirs:   nil,
			SkillsDir:    ".crush/skills",
			Priority:     530,
			RunnableHint: false,
		},
		{
			ID:           "deepagents",
			Name:         "Deep Agents",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".deepagents"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     531,
			RunnableHint: false,
		},
		{
			ID:           "devin",
			Name:         "Devin for Terminal",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   []string{"devin"},
			SkillsDir:    ".devin/skills",
			Priority:     532,
			RunnableHint: false,
		},
		{
			ID:           "dexto",
			Name:         "Dexto",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".dexto"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     533,
			RunnableHint: false,
		},
		{
			ID:           "droid",
			Name:         "Droid",
			Bins:         []string{"droid"},
			EnvBin:       "KIN_DROID_BIN",
			HomeDirs:     []string{".factory"},
			ConfigDirs:   nil,
			SkillsDir:    ".factory/skills",
			Priority:     35,
			RunnableHint: true,
		},
		{
			ID:           "eve",
			Name:         "Eve",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    "agent/skills",
			Priority:     535,
			RunnableHint: false,
		},
		{
			ID:           "firebender",
			Name:         "Firebender",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".firebender"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     536,
			RunnableHint: false,
		},
		{
			ID:           "forgecode",
			Name:         "ForgeCode",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".forge"},
			ConfigDirs:   nil,
			SkillsDir:    ".forge/skills",
			Priority:     537,
			RunnableHint: false,
		},
		{
			ID:           "github-copilot",
			Name:         "GitHub Copilot",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".copilot"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     538,
			RunnableHint: false,
		},
		{
			ID:           "hermes-agent",
			Name:         "Hermes Agent",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    ".hermes/skills",
			Priority:     539,
			RunnableHint: false,
		},
		{
			ID:           "iflow-cli",
			Name:         "iFlow CLI",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".iflow"},
			ConfigDirs:   nil,
			SkillsDir:    ".iflow/skills",
			Priority:     540,
			RunnableHint: false,
		},
		{
			ID:           "inference-sh",
			Name:         "inference.sh",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".inferencesh"},
			ConfigDirs:   nil,
			SkillsDir:    ".inferencesh/skills",
			Priority:     541,
			RunnableHint: false,
		},
		{
			ID:           "jazz",
			Name:         "Jazz",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".jazz"},
			ConfigDirs:   nil,
			SkillsDir:    ".jazz/skills",
			Priority:     542,
			RunnableHint: false,
		},
		{
			ID:           "junie",
			Name:         "Junie",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".junie"},
			ConfigDirs:   nil,
			SkillsDir:    ".junie/skills",
			Priority:     543,
			RunnableHint: false,
		},
		{
			ID:           "kimi-code-cli",
			Name:         "Kimi Code CLI",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".kimi-code", ".kimi"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     544,
			RunnableHint: false,
		},
		{
			ID:           "kiro-cli",
			Name:         "Kiro CLI",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".kiro"},
			ConfigDirs:   nil,
			SkillsDir:    ".kiro/skills",
			Priority:     545,
			RunnableHint: false,
		},
		{
			ID:           "kode",
			Name:         "Kode",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".kode"},
			ConfigDirs:   nil,
			SkillsDir:    ".kode/skills",
			Priority:     546,
			RunnableHint: false,
		},
		{
			ID:           "lingma",
			Name:         "Lingma",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".lingma"},
			ConfigDirs:   nil,
			SkillsDir:    ".lingma/skills",
			Priority:     547,
			RunnableHint: false,
		},
		{
			ID:           "loaf",
			Name:         "Loaf",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".loaf"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     548,
			RunnableHint: false,
		},
		{
			ID:           "mcpjam",
			Name:         "MCPJam",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".mcpjam"},
			ConfigDirs:   nil,
			SkillsDir:    ".mcpjam/skills",
			Priority:     549,
			RunnableHint: false,
		},
		{
			ID:           "mistral-vibe",
			Name:         "Mistral Vibe",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    ".vibe/skills",
			Priority:     550,
			RunnableHint: false,
		},
		{
			ID:           "moxby",
			Name:         "Moxby",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".moxby"},
			ConfigDirs:   nil,
			SkillsDir:    ".moxby/skills",
			Priority:     551,
			RunnableHint: false,
		},
		{
			ID:           "mux",
			Name:         "Mux",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".mux"},
			ConfigDirs:   nil,
			SkillsDir:    ".mux/skills",
			Priority:     552,
			RunnableHint: false,
		},
		{
			ID:           "neovate",
			Name:         "Neovate",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".neovate"},
			ConfigDirs:   nil,
			SkillsDir:    ".neovate/skills",
			Priority:     553,
			RunnableHint: false,
		},
		{
			ID:           "ona",
			Name:         "Ona",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".ona"},
			ConfigDirs:   nil,
			SkillsDir:    ".ona/skills",
			Priority:     554,
			RunnableHint: false,
		},
		{
			ID:           "openhands",
			Name:         "OpenHands",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".openhands"},
			ConfigDirs:   nil,
			SkillsDir:    ".openhands/skills",
			Priority:     555,
			RunnableHint: false,
		},
		{
			ID:           "pi",
			Name:         "Pi",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".pi/agent"},
			ConfigDirs:   nil,
			SkillsDir:    ".pi/skills",
			Priority:     556,
			RunnableHint: false,
		},
		{
			ID:           "pochi",
			Name:         "Pochi",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".pochi"},
			ConfigDirs:   nil,
			SkillsDir:    ".pochi/skills",
			Priority:     557,
			RunnableHint: false,
		},
		{
			ID:           "reasonix",
			Name:         "Reasonix",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".reasonix"},
			ConfigDirs:   nil,
			SkillsDir:    ".reasonix/skills",
			Priority:     558,
			RunnableHint: false,
		},
		{
			ID:           "replit",
			Name:         "Replit",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     559,
			RunnableHint: false,
		},
		{
			ID:           "roo",
			Name:         "Roo Code",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".roo"},
			ConfigDirs:   nil,
			SkillsDir:    ".roo/skills",
			Priority:     560,
			RunnableHint: false,
		},
		{
			ID:           "rovodev",
			Name:         "Rovo Dev",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".rovodev"},
			ConfigDirs:   nil,
			SkillsDir:    ".rovodev/skills",
			Priority:     561,
			RunnableHint: false,
		},
		{
			ID:           "tabnine-cli",
			Name:         "Tabnine CLI",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".tabnine"},
			ConfigDirs:   nil,
			SkillsDir:    ".tabnine/agent/skills",
			Priority:     562,
			RunnableHint: false,
		},
		{
			ID:           "terramind",
			Name:         "Terramind",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".terramind"},
			ConfigDirs:   nil,
			SkillsDir:    ".terramind/skills",
			Priority:     563,
			RunnableHint: false,
		},
		{
			ID:           "tinycloud",
			Name:         "Tinycloud",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".tinycloud"},
			ConfigDirs:   nil,
			SkillsDir:    ".tinycloud/skills",
			Priority:     564,
			RunnableHint: false,
		},
		{
			ID:           "trae",
			Name:         "Trae",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".trae"},
			ConfigDirs:   nil,
			SkillsDir:    ".trae/skills",
			Priority:     565,
			RunnableHint: false,
		},
		{
			ID:           "trae-cn",
			Name:         "Trae CN",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".trae-cn"},
			ConfigDirs:   nil,
			SkillsDir:    ".trae/skills",
			Priority:     566,
			RunnableHint: false,
		},
		{
			ID:           "warp",
			Name:         "Warp",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".warp"},
			ConfigDirs:   nil,
			SkillsDir:    ".agents/skills",
			Priority:     567,
			RunnableHint: false,
		},
		{
			ID:           "zcode",
			Name:         "ZCode",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    ".zcode/skills",
			Priority:     568,
			RunnableHint: false,
		},
		{
			ID:           "zed",
			Name:         "Zed",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     nil,
			ConfigDirs:   []string{"zed"},
			SkillsDir:    ".agents/skills",
			Priority:     569,
			RunnableHint: false,
		},
		{
			ID:           "zencoder",
			Name:         "Zencoder",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".zencoder"},
			ConfigDirs:   nil,
			SkillsDir:    ".zencoder/skills",
			Priority:     570,
			RunnableHint: false,
		},
		{
			ID:           "zenflow",
			Name:         "Zenflow",
			Bins:         nil,
			EnvBin:       "",
			HomeDirs:     []string{".zencoder"},
			ConfigDirs:   nil,
			SkillsDir:    ".zencoder/skills",
			Priority:     571,
			RunnableHint: false,
		},
		{
			ID:           "grok",
			Name:         "Grok",
			Bins:         []string{"grok"},
			EnvBin:       "KIN_GROK_BIN",
			HomeDirs:     nil,
			ConfigDirs:   nil,
			SkillsDir:    "",
			Priority:     30,
			RunnableHint: true,
		},
	}
}
